# Generated by Django 4.2.27 on 2025-12-31 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('agent', 'Agent Commercial')], default='agent', max_length=20, verbose_name='Role'),
        ),
    ]
