# Generated by Django 4.2.27 on 2025-12-26 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Le numero doit commencer par 07 et contenir exactement 10 chiffres.', regex='^07[0-9]{8}$')], verbose_name='Numero')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('assigned', 'Attribue'), ('reserved', 'Reserve'), ('blocked', 'Bloque')], default='available', max_length=20, verbose_name='Statut')),
                ('assigned_to_name', models.CharField(blank=True, max_length=200, verbose_name='Attribue a (Nom)')),
                ('assigned_to_nin', models.CharField(blank=True, max_length=50, verbose_name='NIN du client')),
                ('assigned_date', models.DateTimeField(blank=True, null=True, verbose_name="Date d'attribution")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Derniere modification')),
            ],
            options={
                'verbose_name': 'Numero de telephone',
                'verbose_name_plural': 'Numeros de telephone',
                'ordering': ['number'],
            },
        ),
    ]
