# Generated by Django 4.2.27 on 2025-12-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'offre")),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code offre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('currency', models.CharField(choices=[('DZD', 'Dinar Algerien')], default='DZD', max_length=3, verbose_name='Devise')),
                ('data_allowance_mb', models.PositiveIntegerField(default=0, verbose_name='Data (Mo)')),
                ('voice_minutes', models.PositiveIntegerField(default=0, verbose_name='Minutes voix')),
                ('sms_count', models.PositiveIntegerField(default=0, verbose_name='SMS inclus')),
                ('validity_days', models.PositiveIntegerField(default=30, verbose_name='Validite (jours)')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='Avantages inclus')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Derniere modification')),
            ],
            options={
                'verbose_name': 'Offre',
                'verbose_name_plural': 'Offres',
                'ordering': ['display_order', '-is_featured', 'name'],
            },
        ),
    ]
