# Generated by Django 4.2.27 on 2025-12-31 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Offre', 'verbose_name_plural': 'Offres'},
        ),
        migrations.RemoveField(
            model_name='offer',
            name='is_featured',
        ),
    ]
