# Generated by Django 4.2.27 on 2025-12-26 19:36

import apps.contracts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phone_numbers', '0001_initial'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Numero de contrat')),
                ('customer_first_name', models.CharField(max_length=100, verbose_name='Prenom')),
                ('customer_last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('customer_first_name_ar', models.CharField(blank=True, max_length=100, verbose_name='Prenom (Arabe)')),
                ('customer_last_name_ar', models.CharField(blank=True, max_length=100, verbose_name='Nom (Arabe)')),
                ('customer_birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('customer_birth_place', models.CharField(blank=True, max_length=200, verbose_name='Lieu de naissance')),
                ('customer_sex', models.CharField(blank=True, max_length=10, verbose_name='Sexe')),
                ('customer_nin', models.CharField(max_length=50, verbose_name='NIN')),
                ('customer_id_number', models.CharField(max_length=50, verbose_name='Numero CNI')),
                ('customer_id_expiry', models.DateField(blank=True, null=True, verbose_name="Date d'expiration CNI")),
                ('customer_daira', models.CharField(blank=True, max_length=100, verbose_name='Daira')),
                ('customer_baladia', models.CharField(blank=True, max_length=100, verbose_name='Commune')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=apps.contracts.models.contract_pdf_path, verbose_name='Fichier PDF')),
                ('customer_photo', models.ImageField(blank=True, null=True, upload_to=apps.contracts.models.contract_photo_path, verbose_name='Photo du client')),
                ('signature_base64', models.TextField(blank=True, verbose_name='Signature (Base64)')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email du client')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email envoye')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi email")),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('signed', 'Signe'), ('validated', 'Valide'), ('cancelled', 'Annule')], default='draft', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Derniere modification')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de signature')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_created', to=settings.AUTH_USER_MODEL, verbose_name='Cree par')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='offers.offer', verbose_name='Offre')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='phone_numbers.phonenumber', verbose_name='Numero attribue')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-created_at'],
            },
        ),
    ]
