# Generated by Django 4.2.27 on 2025-12-31 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='customer_id_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numero CNI'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('validated', 'Valide')], default='validated', max_length=20, verbose_name='Statut'),
        ),
    ]
