# Generated by Django 4.2.27 on 2026-01-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contract_customer_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='customer_address',
            field=models.TextField(blank=True, verbose_name='Adresse du client'),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telephone du client'),
        ),
    ]
