# Generated by Django 4.2.27 on 2026-01-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_customer_address_contract_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='customer_birth_place_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lieu de naissance (Arabe)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer_blood_type',
            field=models.CharField(blank=True, max_length=10, verbose_name='Groupe sanguin'),
        ),
    ]
